apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Updated to 1.5.1"
  labels:
    run: web-app
  name: web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: web-app-dp
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: web-app-dp
    spec:
      containers:
      - image: ikambarov/web-app:1.5.1
        name: web-app
